{{- if .Values.common.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "local-volume-provisioner.fullname" . }}-pv-binding
  labels:
    app.kubernetes.io/name: {{ include "local-volume-provisioner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "local-volume-provisioner.chart" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.daemonset.serviceAccount }}
  namespace: {{ .Values.common.namespace }}
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "local-volume-provisioner.fullname" . }}-node-clusterrole
  labels:
    app.kubernetes.io/name: {{ include "local-volume-provisioner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "local-volume-provisioner.chart" . }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "local-volume-provisioner.fullname" . }}-node-binding
  labels:
    app.kubernetes.io/name: {{ include "local-volume-provisioner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "local-volume-provisioner.chart" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.daemonset.serviceAccount }}
  namespace: {{ .Values.common.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "local-volume-provisioner.fullname" . }}-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
{{- if .Values.common.useJobForCleaning }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.common.namespace }}
  name: {{ include "local-volume-provisioner.fullname" . }}-jobs-role
  labels:
    app.kubernetes.io/name: {{ include "local-volume-provisioner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "local-volume-provisioner.chart" . }}
rules:
- apiGroups:
    - 'batch'
  resources:
    - jobs
  verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.common.namespace }}
  name: {{ include "local-volume-provisioner.fullname" . }}-jobs-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "local-volume-provisioner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "local-volume-provisioner.chart" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.daemonset.serviceAccount }}
  namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ include "local-volume-provisioner.fullname" . }}-jobs-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- if .Values.common.podSecurityPolicy }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.common.namespace }}
  name: {{ include "local-volume-provisioner.fullname" . }}-psp-role
  labels:
    app.kubernetes.io/name: {{ include "local-volume-provisioner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "local-volume-provisioner.chart" . }}
rules:
- apiGroups:
    - policy
  resources:
    - podsecuritypolicies
  resourceNames:
    - {{ include "local-volume-provisioner.fullname" . }}-psp
  verbs:
    - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Values.common.namespace }}
  name: {{ include "local-volume-provisioner.fullname" . }}-psp-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "local-volume-provisioner.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "local-volume-provisioner.chart" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.daemonset.serviceAccount }}
  namespace: {{ .Values.common.namespace }}
roleRef:
  kind: Role
  name: {{ include "local-volume-provisioner.fullname" . }}-psp-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
